- name: Practicing on Ansible
  hosts: all
  connection: local
  tasks:
    - name: Print Vegetable Names
      ansible.builtin.debug:
        msg: Vegetable-Carrot

    - name: Print Fruit Names
      ansible.builtin.debug:
        msg: Fruit-Mango